sudo: required
services:
  - docker

before_install:
  - docker build -t brhamill/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true brhamill/react-test npm test

after_success:
  - docker build -t brhamill/multi-client ./client
  - docker build -t brhamill/multi-nginx ./nginx
  - docker build -t brhamill/multi-server ./server
  - docker build -t brhamill/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push brhamill/multi-client
  - docker push brhamill/multi-nginx
  - docker push brhamill/multi-server
  - docker push brhamill/multi-worker
 
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-890187507100
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY